name: CI/CD - democyber

# Trigger the workflow on push or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/democyber:latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

        # Compile Java code
      - name: Compile Java
        run: mvn compile

      # Build Maven
      - name: Build Java project with Maven
        run: mvn clean package

       # Gitleaks scan (before compila�on)
      - name: Run Gitleaks scan
        Suses: zricethezav/gitleaks-ac�on@v2

        # Upload the Gitleaks report
      - name: Upload Gitleaks report
        uses: ac�ons/upload-ar�fact@v4
        with:
          name: gitleaks-report
          path: results.sarif

